import { ChakraProvider, ColorModeScript } from "@chakra-ui/react";
import "./styles/global.css";
import { Metadata } from "next";
import theme from "./theme";
import NavBar from "./components/nav-bar";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>
        <ChakraProvider theme={theme}>
          <NavBar />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
